#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef SENSORSWAVESDK_SWIFT_H
#define SENSORSWAVESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SensorswaveSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// 日志级别枚举
typedef SWIFT_ENUM(NSInteger, LogLevel, open) {
  LogLevelVerbose = 0,
  LogLevelDebug = 1,
  LogLevelInfo = 2,
  LogLevelWarning = 3,
  LogLevelError = 4,
  LogLevelNone = 5,
};

@class NSString;
@class SensorswaveConfig;
/// Sensorswave iOS SDK 主类
/// 提供事件追踪、用户识别等核心功能
SWIFT_CLASS("_TtC14SensorswaveSDK11Sensorswave")
@interface Sensorswave : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Sensorswave * _Nonnull _shared;)
+ (Sensorswave * _Nonnull)_shared SWIFT_WARN_UNUSED_RESULT;
/// 获取Sensorswave实例
///
/// returns:
/// Sensorswave单例实例
+ (Sensorswave * _Nonnull)getInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 初始化SDK
/// \param sourceToken API令牌
///
/// \param config 配置信息
///
///
/// returns:
/// Sensorswave实例（告诉编译器这个方法的返回值可以被忽略）
- (Sensorswave * _Nonnull)setupWithSourceToken:(NSString * _Nonnull)sourceToken config:(SensorswaveConfig * _Nonnull)config;
/// 高级上报方式 - 完整事件对象
/// \param eventData 完整的事件对象
///
- (void)trackWithEventData:(NSDictionary<NSString *, id> * _Nonnull)eventData;
/// 追踪自定义事件
/// \param eventName 事件名称
///
/// \param properties 事件属性
///
- (void)trackEventWithEventName:(NSString * _Nonnull)eventName properties:(NSDictionary<NSString *, id> * _Nonnull)properties;
/// 设置用户属性（如果存在则覆盖）
/// \param properties 用户属性
///
- (void)profileSet:(NSDictionary<NSString *, id> * _Nonnull)properties;
/// 设置一次性用户属性（如果不存在则设置，存在就不设置）
/// \param properties 用户属性
///
- (void)profileSetOnce:(NSDictionary<NSString *, id> * _Nonnull)properties;
/// 对数值用户属性值进行累加
/// \param properties 用户属性键值对，值必须为数值类型
///
- (void)profileIncrementWithProperties:(NSDictionary<NSString *, id> * _Nonnull)properties;
/// 对List类型的用户属性进行追加新的属性值，不会进行去重操作
/// \param properties 用户属性键值对，值必须为列表类型
///
- (void)profileAppendWithProperties:(NSDictionary<NSString *, id> * _Nonnull)properties;
/// 对List类型的用户属性进行追加新的属性值并进行去重操作
/// \param properties 用户属性键值对，值必须为列表类型
///
- (void)profileUnionWithProperties:(NSDictionary<NSString *, id> * _Nonnull)properties;
/// 将对应用户的属性值置为NULL
/// \param key 要置空的属性键
///
- (void)profileUnsetWithKey:(NSString * _Nonnull)key;
/// 将对应用户的属性值置为NULL
/// \param keys 要置空的属性键列表
///
- (void)profileUnsetWithKeys:(NSArray<NSString *> * _Nonnull)keys;
/// 删除一条完整的用户属性信息
- (void)profileDelete;
/// 注册公共属性
/// \param properties 公共属性
///
- (void)registerCommonPropertiesWithProperties:(NSDictionary<NSString *, id> * _Nonnull)properties;
/// 清除公共属性
/// \param keys 要清除的属性键列表
///
- (void)clearCommonPropertiesWithKeys:(NSArray<NSString *> * _Nonnull)keys;
/// 设置登录用户ID并发送绑定事件
/// \param loginId 登录用户ID
///
- (void)identifyWithLoginId:(NSString * _Nonnull)loginId;
/// 只设置登录用户ID，不发送绑定事件
/// \param loginId 登录用户ID
///
- (void)setLoginIdWithLoginId:(NSString * _Nonnull)loginId;
/// 获取匿名ID
///
/// returns:
/// 匿名ID
- (NSString * _Nonnull)getAnonId SWIFT_WARN_UNUSED_RESULT;
/// 获取登录用户ID
///
/// returns:
/// 登录用户ID
- (NSString * _Nonnull)getLoginId SWIFT_WARN_UNUSED_RESULT;
/// 确保功能标志准备就绪
/// \param callback 功能标志就绪后的回调函数
///
- (void)onFeatureFlagsWithCallback:(void (^ _Nonnull)(void))callback;
/// 手动设置当前页面标题
/// \param pageTitle 页面标题
///
- (void)setCurrentPageTitle:(NSString * _Nonnull)pageTitle;
/// 手动设置前向页面标题
/// \param referrerTitle 前向页面标题
///
- (void)setReferrerTitle:(NSString * _Nonnull)referrerTitle;
/// 获取当前页面标题
///
/// returns:
/// 当前页面标题
- (NSString * _Nonnull)getCurrentPageTitle SWIFT_WARN_UNUSED_RESULT;
/// 获取前向页面标题
///
/// returns:
/// 前向页面标题
- (NSString * _Nonnull)getReferrerTitle SWIFT_WARN_UNUSED_RESULT;
/// 检查功能开关（A/B 测试）
/// \param key 功能开关的键名
///
/// \param callback 回调函数，返回功能开关的状态（true=启用，false=禁用）
///
- (void)checkFeatureGateWithKey:(NSString * _Nonnull)key callback:(void (^ _Nonnull)(BOOL))callback;
/// 获取实验配置（A/B 测试）
/// \param key 实验的键名
///
/// \param callback 回调函数，返回实验配置（字典）或 nil
///
- (void)getExperimentWithKey:(NSString * _Nonnull)key callback:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable))callback;
@end

/// Sensorswave SDK 配置类
/// 提供SDK初始化所需的各种配置参数
SWIFT_CLASS("_TtC14SensorswaveSDK17SensorswaveConfig")
@interface SensorswaveConfig : NSObject
/// 是否开启调试模式
@property (nonatomic) BOOL debug;
/// Source令牌
@property (nonatomic, copy) NSString * _Nonnull sourceToken;
/// API主机地址
@property (nonatomic, copy) NSString * _Nonnull apiHost;
/// 是否自动采集数据
@property (nonatomic) BOOL autoCapture;
/// 是否启用 AB
@property (nonatomic) BOOL enableAB;
/// 实验刷新间隔（毫秒）
@property (nonatomic) NSTimeInterval abRefreshInterval;
/// 是否启用批量发送
@property (nonatomic) BOOL batchSend;
/// 是否启用点击追踪
@property (nonatomic) BOOL enableClickTrack;
/// 最大队列大小
@property (nonatomic) NSInteger maxQueueSize;
/// 请求超时时间（毫秒）
@property (nonatomic) NSTimeInterval requestTimeout;
/// 验证配置是否有效
///
/// returns:
/// 配置是否有效
- (BOOL)isValid SWIFT_WARN_UNUSED_RESULT;
/// 获取配置摘要信息
///
/// returns:
/// 配置摘要字典
- (NSDictionary<NSString *, id> * _Nonnull)getConfigSummary SWIFT_WARN_UNUSED_RESULT;
/// 初始化方法
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 日志记录工具
SWIFT_CLASS("_TtC14SensorswaveSDK17SensorswaveLogger")
@interface SensorswaveLogger : NSObject
/// 设置日志级别
/// \param level 日志级别
///
+ (void)setLogLevel:(enum LogLevel)level;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Sensorswave SDK Version
SWIFT_CLASS("_TtC14SensorswaveSDK18SensorswaveVersion")
@interface SensorswaveVersion : NSObject
/// Major version
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger major;)
+ (NSInteger)major SWIFT_WARN_UNUSED_RESULT;
/// Minor version
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger minor;)
+ (NSInteger)minor SWIFT_WARN_UNUSED_RESULT;
/// Patch version
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger patch;)
+ (NSInteger)patch SWIFT_WARN_UNUSED_RESULT;
/// Full version string (e.g., “1.0.0”)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull string;)
+ (NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
